spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springdata
    username: java
    password: ndjc@1483
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
